### ISSUE TITLE
package cloud repository

### ISSUE THREAD

**Issue by nevesenin** [skaes/logjam-tools#12]
Hi,

I really like the idea to install just one logjam deb package instead of installing all the tools and dependencies manually. Currently the installation failed on ubuntu trusty because of the missing logjam-libs_0.2-1 package. It would be great if you could provide the missing package.

Regards

**Comment by skaes** [comment]
I'm in the process of releasing a new version. Should be available soon.

**Comment by skaes** [comment]
Sorry, I lost track of this. Has it been resolved?

**Comment by nevesenin** [comment]
Yes, thanks!
